import canonicalLaneMathlib.AdmissibleClass
import HautevilleHouse.DevelopmentalBiologyNeuralCrestDevelopmentTheoremCanonicalLaneLean.AdmissibleClass
import HautevilleHouse.DevelopmentalBiologyNeuralCrestDevelopmentTheoremCanonicalLaneLean.BridgeLemmas
import HautevilleHouse.DevelopmentalBiologyNeuralCrestDevelopmentTheoremCanonicalLaneLean.GateLemmas

namespace HautevilleHouse
namespace DevelopmentalBiologyNeuralCrestDevelopmentTheoremCanonicalLaneLean

def ConstrainedNeuralCrestClosure (A : AdmissibleClass) : Prop :=
  bridgeClosed A ∧ gateClosed A

theorem constrained_neural_crest_endgame (A : AdmissibleClass) : ConstrainedNeuralCrestClosure A := by
  exact And.intro (bridge_from_admissible_class A) (gate_from_admissible_class A)

end DevelopmentalBiologyNeuralCrestDevelopmentTheoremCanonicalLaneLean
end HautevilleHouse